// Stable projectile archetypes shared by deterministic simulation and rendering.

import * as fx from './fixed.js';

export const PROJECTILE = {
  ARROW: 0,
  BOLT: 1,
  ORB: 2,
  ROCK: 3,
  FIREBALL: 4,
  SPORE_STREAM: 5,
  HOLY_SLASH: 6,
  SHADOW_BOLT: 7,
  ICE_BOLT: 8,
  LOCUST_SWARM: 9,
};

export const PROJECTILE_MESH = {
  ARROW: 0,
  ORB: 1,
  ROCK: 2,
};

/** Gameplay fields are fixed-point/tick based; render fields are cosmetic only. */
export const PROJECTILE_DEFS = [
  {
    id: PROJECTILE.ARROW,
    name: 'Arrow',
    speed: fx.fromFloat(3),
    maxTicks: 32,
    hitRadius: fx.fromFloat(1.5),
    homing: 1,
    blockedByTerrain: 0,
    pierce: 1,
    splashRadius: 0,
    mesh: PROJECTILE_MESH.ARROW,
    scale: [0.18, 0.18, 1.8],
    color: [0.58, 0.34, 0.12],
    // Bow shot: loft then drop into the target (not a ground-hugging skim).
    lob: 1,
    launchHeight: 3.8,
    impactHeight: 2.3,
    arcHeight: 5,
    lobRangeFactor: 0.2,
    renderCapacity: 32768,
  },
  {
    id: PROJECTILE.BOLT,
    name: 'Bolt',
    speed: fx.fromFloat(8),
    maxTicks: 22,
    hitRadius: fx.fromFloat(1.3),
    homing: 0,
    blockedByTerrain: 0,
    pierce: 1,
    splashRadius: 0,
    mesh: PROJECTILE_MESH.ARROW,
    scale: [0.22, 0.22, 1.35],
    color: [0.38, 0.28, 0.18],
    launchHeight: 3.2,
    arcHeight: 0.35,
    renderCapacity: 8192,
  },
  {
    id: PROJECTILE.ORB,
    name: 'Orb',
    speed: fx.fromFloat(4.5),
    maxTicks: 36,
    hitRadius: fx.fromFloat(2),
    homing: 1,
    blockedByTerrain: 0,
    pierce: 1,
    splashRadius: 0,
    mesh: PROJECTILE_MESH.ORB,
    scale: [0.8, 0.8, 0.8],
    color: [0.25, 0.62, 1],
    launchHeight: 3.5,
    arcHeight: 0.8,
    renderCapacity: 8192,
  },
  {
    id: PROJECTILE.ROCK,
    name: 'Rock',
    speed: fx.fromFloat(3.5),
    maxTicks: 48,
    hitRadius: fx.fromFloat(2.5),
    homing: 0,
    blockedByTerrain: 1,
    pierce: 1,
    splashRadius: fx.fromFloat(5),
    mesh: PROJECTILE_MESH.ROCK,
    scale: [1.1, 1.1, 1.1],
    color: [0.3, 0.27, 0.24],
    launchHeight: 4,
    arcHeight: 5,
    renderCapacity: 4096,
  },
  {
    id: PROJECTILE.FIREBALL,
    name: 'Fireball',
    // Slower than bolts so the lob reads in flight.
    speed: fx.fromFloat(5),
    // Long throws need room for a full arc lifetime (render loft scales with this).
    maxTicks: 96,
    hitRadius: fx.fromFloat(2),
    homing: 0,
    blockedByTerrain: 0,
    pierce: 1,
    // v1 ≈ 1.25 tiles × 4 world units.
    splashRadius: fx.fromFloat(5),
    friendlyFireMultiplier: 0.25,
    ignitesTrees: 1,
    /** Leave a short damaging ground-fire patch at impact. */
    leavesGroundFire: 1,
    /** Splash also yeets units (shorter fire-trail lob). */
    blastLob: 1,
    // Aim drift as a fraction of throw range (longer shots wander more).
    aimScatter: fx.fromFloat(0.12),
    mesh: PROJECTILE_MESH.ORB,
    scale: [0.95, 0.95, 0.95],
    color: [1, 0.42, 0.06],
    // Thrown from the hand, crashes into the ground (not a dolphin hop).
    lob: 1,
    launchHeight: 4.2,
    // Ball center near the dirt so the splash reads as a ground hit.
    impactHeight: 0.35,
    arcHeight: 11,
    renderCapacity: 4096,
  },
  {
    id: PROJECTILE.SPORE_STREAM,
    name: 'SporeStream',
    speed: fx.fromFloat(3.8),
    maxTicks: 42,
    hitRadius: fx.fromFloat(3.2),
    homing: 1,
    blockedByTerrain: 0,
    pierce: 6,
    splashRadius: 0,
    pathHit: 1,
    wanderPeriod: 3,
    wanderAmount: fx.fromFloat(2.4),
    mesh: PROJECTILE_MESH.ORB,
    scale: [0.55, 0.55, 0.55],
    color: [0.42, 0.78, 0.38],
    launchHeight: 2.8,
    arcHeight: 0.45,
    renderCapacity: 4096,
  },
  {
    id: PROJECTILE.HOLY_SLASH,
    name: 'HolySlash',
    speed: fx.fromFloat(14),
    maxTicks: 18,
    hitRadius: fx.fromFloat(2.2),
    homing: 1,
    blockedByTerrain: 0,
    pierce: 1,
    splashRadius: 0,
    mesh: PROJECTILE_MESH.ORB,
    scale: [0.35, 0.9, 1.6],
    color: [1, 0.96, 0.78],
    launchHeight: 3.6,
    arcHeight: 0.15,
    renderCapacity: 4096,
  },
  {
    id: PROJECTILE.SHADOW_BOLT,
    name: 'ShadowBolt',
    speed: fx.fromFloat(4.2),
    maxTicks: 36,
    hitRadius: fx.fromFloat(2),
    homing: 1,
    blockedByTerrain: 0,
    pierce: 1,
    splashRadius: 0,
    appliesDot: 1,
    mesh: PROJECTILE_MESH.ORB,
    scale: [0.72, 0.72, 0.72],
    color: [0.06, 0.03, 0.1],
    launchHeight: 3.5,
    arcHeight: 0.7,
    renderCapacity: 4096,
  },
  {
    id: PROJECTILE.ICE_BOLT,
    name: 'IceBolt',
    speed: fx.fromFloat(5.5),
    maxTicks: 30,
    hitRadius: fx.fromFloat(1.6),
    homing: 1,
    blockedByTerrain: 0,
    pierce: 1,
    splashRadius: 0,
    appliesFrost: 1,
    mesh: PROJECTILE_MESH.ARROW,
    scale: [0.2, 0.2, 1.55],
    color: [0.55, 0.88, 1],
    launchHeight: 3.4,
    arcHeight: 0.5,
    renderCapacity: 4096,
  },
  {
    id: PROJECTILE.LOCUST_SWARM,
    name: 'LocustSwarm',
    speed: fx.fromFloat(4.0),
    maxTicks: 38,
    hitRadius: fx.fromFloat(2.2),
    homing: 1,
    blockedByTerrain: 0,
    pierce: 1,
    splashRadius: 0,
    appliesDistract: 1,
    mesh: PROJECTILE_MESH.ORB,
    scale: [0.35, 0.35, 0.35],
    color: [0.18, 0.22, 0.1],
    launchHeight: 2.6,
    arcHeight: 0.55,
    renderCapacity: 4096,
  },
];

export function getProjectileDef(typeId) {
  return PROJECTILE_DEFS[typeId] ?? PROJECTILE_DEFS[PROJECTILE.ARROW];
}
