// Unit type definitions — single source of truth for sim stats.
// Render reads size + color from here; gameplay systems read hp/speed/combat.

import * as fx from './fixed.js';
import { PROJECTILE } from './projectileTypes.js';

export const UNIT = {
  VILLAGER: 0,
  WARRIOR: 1,
  ARCHER: 2,
  WARLOCK: 3,
  PRIEST: 4,
  MYCO: 5,
  SHAMAN: 6,
  WIZARD: 7,
  MONK: 8,
  ENGINEER: 9,
  WAGON: 10,
  DIRIGIBLE: 11,
  APC: 12,
};

export const ATTACK_DELIVERY = {
  MELEE: 0,
  PROJECTILE: 1,
};

/** @type {ReadonlyArray<{ id: number, name: string, category: string, hp: number, speed: number, size: number, footprint?: number, pickRadius: number, pickHeight: number, color: [number, number, number], attackDamage: number, attackRange: number, attackCooldown: number, aggroRange: number, attackDelivery: number, projectileType: number, minRange: number, preferredRange: number, primaryAbility: string | null, transportCapacity?: number, mechanical?: boolean, fly?: boolean, canHaul?: boolean }>} */
export const UNIT_DEFS = [
  {
    id: UNIT.VILLAGER,
    name: 'Villager',
    category: 'civilian',
    hp: 50,
    speed: fx.fromFloat(2.0),
    size: 4.5,
    pickRadius: 1.4,
    pickHeight: 0.95,
    color: [0.82, 0.74, 0.42],
    attackDamage: 3,
    attackRange: fx.fromFloat(2.0),
    attackCooldown: 40,
    aggroRange: fx.fromFloat(0),
    attackDelivery: ATTACK_DELIVERY.MELEE,
    projectileType: -1,
    minRange: 0,
    preferredRange: fx.fromFloat(2),
    primaryAbility: null,
  },
  {
    id: UNIT.WARRIOR,
    name: 'Warrior',
    category: 'military',
    hp: 120,
    speed: fx.fromFloat(2.4),
    size: 7.5,
    pickRadius: 1.8,
    pickHeight: 1.1,
    color: [0.82, 0.22, 0.18],
    attackDamage: 10,
    attackRange: fx.fromFloat(2.5),
    attackCooldown: 28,
    // Must reach archer stand-off (~57) so melee can auto-acquire / chase.
    aggroRange: fx.fromFloat(55),
    attackDelivery: ATTACK_DELIVERY.MELEE,
    projectileType: -1,
    minRange: 0,
    preferredRange: fx.fromFloat(2.5),
    primaryAbility: null,
  },
  {
    id: UNIT.ARCHER,
    name: 'Archer',
    category: 'military',
    hp: 65,
    speed: fx.fromFloat(2.8),
    size: 5.5,
    pickRadius: 1.6,
    pickHeight: 1.05,
    color: [0.28, 0.62, 0.32],
    attackDamage: 8,
    attackRange: fx.fromFloat(70),
    attackCooldown: 40,
    aggroRange: fx.fromFloat(60),
    attackDelivery: ATTACK_DELIVERY.PROJECTILE,
    projectileType: PROJECTILE.ARROW,
    minRange: fx.fromFloat(5),
    preferredRange: fx.fromFloat(57.5),
    primaryAbility: null,
  },
  {
    id: UNIT.WARLOCK,
    name: 'Warlock',
    category: 'military',
    hp: 55,
    speed: fx.fromFloat(2.2),
    size: 5.5,
    pickRadius: 1.6,
    pickHeight: 1.05,
    color: [0.55, 0.22, 0.72],
    attackDamage: 9,
    attackRange: fx.fromFloat(55),
    attackCooldown: 36,
    aggroRange: fx.fromFloat(50),
    attackDelivery: ATTACK_DELIVERY.PROJECTILE,
    projectileType: PROJECTILE.SHADOW_BOLT,
    minRange: fx.fromFloat(4),
    preferredRange: fx.fromFloat(42),
    primaryAbility: 'warlock_fireball',
  },
  {
    id: UNIT.PRIEST,
    name: 'Priest',
    category: 'military',
    hp: 50,
    speed: fx.fromFloat(2.3),
    size: 5.2,
    pickRadius: 1.55,
    pickHeight: 1.05,
    color: [0.92, 0.88, 0.72],
    attackDamage: 6,
    attackRange: fx.fromFloat(45),
    attackCooldown: 44,
    aggroRange: fx.fromFloat(42),
    attackDelivery: ATTACK_DELIVERY.PROJECTILE,
    projectileType: PROJECTILE.HOLY_SLASH,
    minRange: fx.fromFloat(4),
    preferredRange: fx.fromFloat(35),
    primaryAbility: 'holy_armor',
  },
  {
    id: UNIT.MYCO,
    name: 'Myco',
    category: 'military',
    hp: 60,
    speed: fx.fromFloat(2.1),
    size: 5.4,
    pickRadius: 1.6,
    pickHeight: 1.0,
    color: [0.45, 0.72, 0.55],
    attackDamage: 5,
    attackRange: fx.fromFloat(40),
    attackCooldown: 42,
    aggroRange: fx.fromFloat(38),
    attackDelivery: ATTACK_DELIVERY.PROJECTILE,
    projectileType: PROJECTILE.SPORE_STREAM,
    minRange: fx.fromFloat(3),
    preferredRange: fx.fromFloat(30),
    primaryAbility: 'spore_bloom',
  },
  {
    id: UNIT.SHAMAN,
    name: 'Shaman',
    category: 'military',
    hp: 65,
    speed: fx.fromFloat(2.3),
    size: 5.5,
    pickRadius: 1.6,
    pickHeight: 1.05,
    color: [0.35, 0.55, 0.38],
    attackDamage: 5,
    attackRange: fx.fromFloat(42),
    attackCooldown: 40,
    aggroRange: fx.fromFloat(40),
    attackDelivery: ATTACK_DELIVERY.PROJECTILE,
    projectileType: PROJECTILE.LOCUST_SWARM,
    minRange: fx.fromFloat(3),
    preferredRange: fx.fromFloat(32),
    primaryAbility: 'plague_of_frogs',
  },
  {
    id: UNIT.WIZARD,
    name: 'Wizard',
    category: 'military',
    hp: 50,
    speed: fx.fromFloat(2.2),
    size: 5.5,
    pickRadius: 1.6,
    pickHeight: 1.05,
    color: [0.42, 0.62, 0.95],
    attackDamage: 10,
    attackRange: fx.fromFloat(58),
    attackCooldown: 42,
    aggroRange: fx.fromFloat(52),
    attackDelivery: ATTACK_DELIVERY.PROJECTILE,
    projectileType: PROJECTILE.ICE_BOLT,
    minRange: fx.fromFloat(4),
    preferredRange: fx.fromFloat(45),
    primaryAbility: 'wizard_lightning',
  },
  {
    id: UNIT.MONK,
    name: 'Monk',
    category: 'military',
    hp: 70,
    speed: fx.fromFloat(2.6),
    size: 5.2,
    pickRadius: 1.55,
    pickHeight: 1.05,
    color: [0.78, 0.55, 0.28],
    attackDamage: 10,
    attackRange: fx.fromFloat(2.2),
    attackCooldown: 32,
    aggroRange: fx.fromFloat(40),
    attackDelivery: ATTACK_DELIVERY.MELEE,
    projectileType: -1,
    minRange: 0,
    preferredRange: fx.fromFloat(2.2),
    primaryAbility: null,
  },
  {
    id: UNIT.ENGINEER,
    name: 'Engineer',
    category: 'civilian',
    hp: 50,
    speed: fx.fromFloat(2.1),
    size: 5.0,
    pickRadius: 1.5,
    pickHeight: 1.0,
    color: [0.55, 0.58, 0.62],
    attackDamage: 0,
    attackRange: fx.fromFloat(3.5),
    attackCooldown: 40,
    aggroRange: fx.fromFloat(0),
    attackDelivery: ATTACK_DELIVERY.MELEE,
    projectileType: -1,
    minRange: 0,
    preferredRange: fx.fromFloat(3.5),
    primaryAbility: null,
  },
  {
    id: UNIT.WAGON,
    name: 'Wagon',
    category: 'vehicle',
    hp: 60,
    speed: fx.fromFloat(2.5),
    size: 9.0,
    /** Ground clearance radius — vehicles need more than size/6 infantry packing. */
    footprint: 6.5,
    pickRadius: 4.5,
    pickHeight: 1.2,
    color: [0.62, 0.42, 0.22],
    attackDamage: 0,
    attackRange: fx.fromFloat(0),
    attackCooldown: 40,
    aggroRange: fx.fromFloat(0),
    attackDelivery: ATTACK_DELIVERY.MELEE,
    projectileType: -1,
    minRange: 0,
    preferredRange: fx.fromFloat(0),
    primaryAbility: null,
    transportCapacity: 4,
    mechanical: true,
    canHaul: true,
  },
  {
    id: UNIT.DIRIGIBLE,
    name: 'Dirigible',
    category: 'air',
    hp: 70,
    speed: fx.fromFloat(3.2),
    size: 12.0,
    footprint: 5.5,
    pickRadius: 4.0,
    pickHeight: 1.4,
    color: [0.72, 0.78, 0.88],
    attackDamage: 0,
    attackRange: fx.fromFloat(0),
    attackCooldown: 40,
    aggroRange: fx.fromFloat(0),
    attackDelivery: ATTACK_DELIVERY.MELEE,
    projectileType: -1,
    minRange: 0,
    preferredRange: fx.fromFloat(0),
    primaryAbility: null,
    transportCapacity: 6,
    mechanical: true,
    fly: true,
  },
  {
    id: UNIT.APC,
    name: 'APC',
    category: 'military',
    hp: 90,
    speed: fx.fromFloat(2.8),
    size: 10.0,
    footprint: 7.0,
    pickRadius: 5.0,
    pickHeight: 1.25,
    color: [0.48, 0.42, 0.28],
    attackDamage: 8,
    attackRange: fx.fromFloat(2.5),
    attackCooldown: 30,
    // Combat transport: fights on order / retaliation, does not idle-hunt.
    aggroRange: fx.fromFloat(0),
    attackDelivery: ATTACK_DELIVERY.MELEE,
    projectileType: -1,
    minRange: 0,
    preferredRange: fx.fromFloat(2.5),
    primaryAbility: null,
    transportCapacity: 6,
    mechanical: true,
  },
];

export function getUnitDef(typeId) {
  return UNIT_DEFS[typeId] ?? UNIT_DEFS[UNIT.VILLAGER];
}

/** Soft personal-space radius (world units). Defaults to infantry size/6 packing. */
export function unitFootprint(typeId) {
  const def = getUnitDef(typeId);
  if (def.footprint != null) return def.footprint;
  return Math.max(1.0, def.size / 6);
}

export function isMilitary(typeId) {
  return getUnitDef(typeId).category === 'military';
}

export function isTransport(typeId) {
  return (getUnitDef(typeId).transportCapacity ?? 0) > 0;
}

export function isMechanical(typeId) {
  return !!getUnitDef(typeId).mechanical;
}

export function isFlyer(typeId) {
  return !!getUnitDef(typeId).fly;
}

/** World-Y loft for flying units (v1 air altitude). */
export const FLY_HEIGHT = 16;
